
import './globals.css'
import type { Metadata } from 'next'




export const metadata: Metadata = {
  title: 'EMNT E-commerce Site',
  description: 'Generated by EMNT with Next JS',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen
       bg-gradient-to-l
        from-cyan-700  to-blue-950 font-poppins'>

        {children}

      </body>
    </html>
  )
}
